In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
community = pd.read_csv('Community_Resource_Information.csv')
community.head(5)

,Contact Type,Contact,Street Address,Phone Number,Notes,Mapped location
0,GED/Education,Christian Women's Job Corp,18 8th Ave. S,(615) 244-3669,women only,NaN
1,Transportation Services,TennCare transportation,NaN,(615) 333-5445,NaN,"Nashville, TN\n(36.166687, -86.779932)"
2,Food,Preston Taylor Ministries,4014 Indiana Ave,(615) 596-4386,community food bank-pantry,"4014 Indiana Ave\nNashville, TN\n(36.157154, -..."
3,Senior/Disabled Housing,Hadley Park Towers,2901 John Merritt Blvd.,(615) 252-3724,housing,"2901 John Merritt Blvd.\nNashville, TN\n(36.16..."
4,Food,Second Harvest BackPack Program,NaN,(615) 329-3491,weekend food for kids,"Nashville, TN\n(36.166687, -86.779932)"

In [3]:
owners = pd.read_csv('Housing_Assistance_Owners.csv')
owners.head(5)

C:\Users\matth\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,disasterNumber,state,county,city,zipCode,validRegistrations,averageFemaInspectedDamage,totalInspected,totalDamage,noFemaInspectedDamage,...,approvedForFemaAssistance,totalApprovedIhpAmount,repairReplaceAmount,rentalAmount,otherNeedsAmount,approvedBetween1And10000,approvedBetween10001And25000,approvedBetween25001AndMax,totalMaxGrants,id
0,1439,TX,Harris (County),HOUSTON,77047,6,1205.226667,6,7231.36,2,...,4,12695.24,7033.24,5662.0,0.00,2,2,0,0,60bb448ca0ee349d71c9185d
1,1439,TX,Harris (County),HOUSTON,77022,5,1414.474000,4,7072.37,1,...,3,8945.23,2467.74,1156.0,5321.49,2,1,0,0,60bb448ca0ee349d71c9184a
2,1439,TX,Jasper (County),KIRBYVILLE,75956,24,2187.857500,23,52508.58,2,...,19,51295.16,30765.80,4092.0,16437.36,16,1,2,0,60bb448ca0ee349d71c91837
3,1439,TX,Harris (County),HOUSTON,77014,2,2379.300000,2,4758.60,0,...,2,8534.10,4366.10,4168.0,0.00,1,1,0,0,60bb448ca0ee349d71c91842
4,1439,TX,Harris (County),JERSEY VILLAGE,77040,2,5823.655000,2,11647.31,0,...,1,2089.50,2089.50,0.0,0.00,1,0,0,0,60bb448ca0ee349d71c91857

In [4]:
public = pd.read_csv('Public_Assistance_Funded_Projects_Details.csv')
public.head(5)

,disasterNumber,declarationDate,incidentType,pwNumber,applicationTitle,applicantId,damageCategoryCode,dcc,damageCategory,projectSize,...,state,stateCode,stateNumberCode,projectAmount,federalShareObligated,totalObligated,obligatedDate,hash,lastRefresh,id
0,1239,1998-08-26T04:00:00.000Z,Severe Storm(s),41,Not Provided,463-99463-00,C - Roads and Bridges,C,Roads and Bridges,Small,...,Texas,TX,48,1489.98,1117.49,1158.77,1998-10-23T11:29:35.000Z,d6d9d778ca297d0fc97b04dfbc9ce269,2021-04-15T16:34:10.154Z,5ee7590f556129600dd511bd
1,1239,1998-08-26T04:00:00.000Z,Severe Storm(s),51,Not Provided,463-99463-00,C - Roads and Bridges,C,Roads and Bridges,Small,...,Texas,TX,48,11300.00,8475.00,8788.01,1998-10-23T11:29:35.000Z,b134f5a24c808f0b3e4330a8e7833c98,2021-04-15T16:34:10.155Z,5ee7590f556129600dd511be
2,1239,1998-08-26T04:00:00.000Z,Severe Storm(s),43,Not Provided,463-99463-00,C - Roads and Bridges,C,Roads and Bridges,Small,...,Texas,TX,48,3486.00,2614.50,2711.06,1998-10-23T11:29:35.000Z,1fc5536c58e82d5371099dbf04cf7101,2021-04-15T16:34:10.154Z,5ee7590f556129600dd511bf
3,1239,1998-08-26T04:00:00.000Z,Severe Storm(s),2,(L),465-19792-01,F - Public Utilities,F,Public Utilities,Large,...,Texas,TX,48,423791.13,317843.35,333171.72,1998-09-17T16:00:59.000Z,6a222a9d0d175f87d0ba16b59d692e0b,2020-06-15T11:18:39.486Z,5ee7590f556129600dd511c1
4,1239,1998-08-26T04:00:00.000Z,Severe Storm(s),47,Not Provided,463-99463-00,C - Roads and Bridges,C,Roads and Bridges,Small,...,Texas,TX,48,3819.67,2864.75,2970.56,1998-10-23T11:29:35.000Z,4965dbca8b235f5399d6be7614262174,2021-04-15T16:34:10.155Z,5ee7590f556129600dd511c0

# Cleaning Public Dataset

In [5]:
# Filtering data down to stateCode TN
public_tn = public[public['stateCode']=='TN']
public_tn.head()

,disasterNumber,declarationDate,incidentType,pwNumber,applicationTitle,applicantId,damageCategoryCode,dcc,damageCategory,projectSize,...,state,stateCode,stateNumberCode,projectAmount,federalShareObligated,totalObligated,obligatedDate,hash,lastRefresh,id
15063,1260,1999-01-15T05:00:00.000Z,Severe Storm(s),3,Electrical Distribution System,000-00145-00,F - Public Utilities,F,Public Utilities,Small,...,Tennessee,TN,47,39852.00,29889.00,31395.41,1999-03-04T20:51:16.000Z,db0922dd54b2383540277e13550b8422,2020-06-15T11:19:16.410Z,5ee75934556129600dd54c97
15064,1260,1999-01-15T05:00:00.000Z,Severe Storm(s),4,DEBRIS FROM ICE STORM,000-00141-00,A - Debris Removal,A,Debris Removal,Large,...,Tennessee,TN,47,98604.00,73953.00,77680.23,1999-03-04T20:51:16.000Z,371ba327f454caddc0181c678a16a65e,2020-06-15T11:19:16.411Z,5ee75934556129600dd54c98
15065,1260,1999-01-15T05:00:00.000Z,Severe Storm(s),8,ICE GENERATED DEBRIS,035-99035-00,A - Debris Removal,A,Debris Removal,Small,...,Tennessee,TN,47,43339.17,32504.38,34142.60,1999-03-04T20:51:16.000Z,afaaddd143fec6237d1dd8a4bcb04aa9,2020-06-15T11:19:16.413Z,5ee75934556129600dd54c99
15066,1260,1999-01-15T05:00:00.000Z,Severe Storm(s),9,"Security Patrols, Search And Rescue",035-99035-00,B - Protective Measures,B,Protective Measures,Small,...,Tennessee,TN,47,9942.81,7457.11,7832.95,1999-03-04T20:51:16.000Z,ed6aa48643af27a3ceb268f66e380237,2020-06-15T11:19:16.414Z,5ee75934556129600dd54c9a
15067,1260,1999-01-15T05:00:00.000Z,Severe Storm(s),12,DEBRIS REMOVAL,035-99035-00,A - Debris Removal,A,Debris Removal,Small,...,Tennessee,TN,47,7983.81,5987.86,6258.51,2000-05-30T23:54:20.000Z,f2c15d25c3e2eaf54b0522dd91c83b17,2020-06-15T11:19:16.415Z,5ee75934556129600dd54c9b

In [6]:
# Filter County to Davidson
public_davidson = public_tn[public_tn['county']=='Davidson']
public_davidson.head()

,disasterNumber,declarationDate,incidentType,pwNumber,applicationTitle,applicantId,damageCategoryCode,dcc,damageCategory,projectSize,...,state,stateCode,stateNumberCode,projectAmount,federalShareObligated,totalObligated,obligatedDate,hash,lastRefresh,id
16950,1275,1999-05-12T04:00:00.000Z,Severe Storm(s),1013,B-1 ROADS AND BRIDGES,037-54780-00,C - Roads and Bridges,C,Roads and Bridges,Small,...,Tennessee,TN,47,2640.85,1980.64,2121.67,1999-06-04T18:03:45.000Z,b37db3f5f1b88ab35108e14c3746cfae,2021-04-15T16:34:18.499Z,5ee75938556129600dd553fa
16951,1275,1999-05-12T04:00:00.000Z,Severe Storm(s),1014,B-1 LARGE PROJECT DEBRIS REMOVAL,037-54780-00,A - Debris Removal,A,Debris Removal,Large,...,Tennessee,TN,47,94148.39,70611.29,74054.13,1999-08-11T23:31:04.000Z,1665905e8c795022e3a2644c9eddbab0,2020-06-15T11:19:20.422Z,5ee75938556129600dd553f7
16954,1275,1999-05-12T04:00:00.000Z,Severe Storm(s),1015,B-1 DEBRIS REMOVAL,037-04620-00,A - Debris Removal,A,Debris Removal,Small,...,Tennessee,TN,47,13570.20,10177.65,10796.46,1999-06-04T18:06:14.000Z,c74141d1f36eaa83f255362c38c2d26a,2020-06-15T11:19:20.427Z,5ee75938556129600dd553fb
16994,1275,1999-05-12T04:00:00.000Z,Severe Storm(s),1062,AIRPORT,037-52008-00,G - Recreational or Other,G,Recreational or Other,Small,...,Tennessee,TN,47,14509.00,10881.75,11430.19,1999-06-07T18:57:04.000Z,29f5e5edcbce7a323ed43632005ad141,2020-06-15T11:19:20.515Z,5ee75938556129600dd55427
16995,1275,1999-05-12T04:00:00.000Z,Severe Storm(s),1059,AIRFIELD LIGHTING AND SIGNS,037-52008-00,G - Recreational or Other,G,Recreational or Other,Small,...,Tennessee,TN,47,15940.00,11955.00,12557.53,1999-06-07T18:57:04.000Z,67e971f8ead9ce670c9578c525833592,2020-06-15T11:19:20.511Z,5ee75938556129600dd55423

In [7]:
# Drop Columns
public_davidson_2 = public_davidson.drop(['stateNumberCode','hash','lastRefresh','id'], axis=1)
public_davidson_2.head()

,disasterNumber,declarationDate,incidentType,pwNumber,applicationTitle,applicantId,damageCategoryCode,dcc,damageCategory,projectSize,county,countyCode,state,stateCode,projectAmount,federalShareObligated,totalObligated,obligatedDate
16950,1275,1999-05-12T04:00:00.000Z,Severe Storm(s),1013,B-1 ROADS AND BRIDGES,037-54780-00,C - Roads and Bridges,C,Roads and Bridges,Small,Davidson,37.0,Tennessee,TN,2640.85,1980.64,2121.67,1999-06-04T18:03:45.000Z
16951,1275,1999-05-12T04:00:00.000Z,Severe Storm(s),1014,B-1 LARGE PROJECT DEBRIS REMOVAL,037-54780-00,A - Debris Removal,A,Debris Removal,Large,Davidson,37.0,Tennessee,TN,94148.39,70611.29,74054.13,1999-08-11T23:31:04.000Z
16954,1275,1999-05-12T04:00:00.000Z,Severe Storm(s),1015,B-1 DEBRIS REMOVAL,037-04620-00,A - Debris Removal,A,Debris Removal,Small,Davidson,37.0,Tennessee,TN,13570.20,10177.65,10796.46,1999-06-04T18:06:14.000Z
16994,1275,1999-05-12T04:00:00.000Z,Severe Storm(s),1062,AIRPORT,037-52008-00,G - Recreational or Other,G,Recreational or Other,Small,Davidson,37.0,Tennessee,TN,14509.00,10881.75,11430.19,1999-06-07T18:57:04.000Z
16995,1275,1999-05-12T04:00:00.000Z,Severe Storm(s),1059,AIRFIELD LIGHTING AND SIGNS,037-52008-00,G - Recreational or Other,G,Recreational or Other,Small,Davidson,37.0,Tennessee,TN,15940.00,11955.00,12557.53,1999-06-07T18:57:04.000Z

In [8]:
# adding column for declartion date as a datetime datatype
public_davidson_2['declaration_date'] = pd.to_datetime(public_davidson_2['declarationDate'])
public_davidson_2.head()

,disasterNumber,declarationDate,incidentType,pwNumber,applicationTitle,applicantId,damageCategoryCode,dcc,damageCategory,projectSize,county,countyCode,state,stateCode,projectAmount,federalShareObligated,totalObligated,obligatedDate,declaration_date
16950,1275,1999-05-12T04:00:00.000Z,Severe Storm(s),1013,B-1 ROADS AND BRIDGES,037-54780-00,C - Roads and Bridges,C,Roads and Bridges,Small,Davidson,37.0,Tennessee,TN,2640.85,1980.64,2121.67,1999-06-04T18:03:45.000Z,1999-05-12 04:00:00+00:00
16951,1275,1999-05-12T04:00:00.000Z,Severe Storm(s),1014,B-1 LARGE PROJECT DEBRIS REMOVAL,037-54780-00,A - Debris Removal,A,Debris Removal,Large,Davidson,37.0,Tennessee,TN,94148.39,70611.29,74054.13,1999-08-11T23:31:04.000Z,1999-05-12 04:00:00+00:00
16954,1275,1999-05-12T04:00:00.000Z,Severe Storm(s),1015,B-1 DEBRIS REMOVAL,037-04620-00,A - Debris Removal,A,Debris Removal,Small,Davidson,37.0,Tennessee,TN,13570.20,10177.65,10796.46,1999-06-04T18:06:14.000Z,1999-05-12 04:00:00+00:00
16994,1275,1999-05-12T04:00:00.000Z,Severe Storm(s),1062,AIRPORT,037-52008-00,G - Recreational or Other,G,Recreational or Other,Small,Davidson,37.0,Tennessee,TN,14509.00,10881.75,11430.19,1999-06-07T18:57:04.000Z,1999-05-12 04:00:00+00:00
16995,1275,1999-05-12T04:00:00.000Z,Severe Storm(s),1059,AIRFIELD LIGHTING AND SIGNS,037-52008-00,G - Recreational or Other,G,Recreational or Other,Small,Davidson,37.0,Tennessee,TN,15940.00,11955.00,12557.53,1999-06-07T18:57:04.000Z,1999-05-12 04:00:00+00:00

In [9]:
# adding column for obligated date as a datetime datatype
public_davidson_2['obligated_date'] = pd.to_datetime(public_davidson_2['obligatedDate'])
public_davidson_2.head()

,disasterNumber,declarationDate,incidentType,pwNumber,applicationTitle,applicantId,damageCategoryCode,dcc,damageCategory,projectSize,county,countyCode,state,stateCode,projectAmount,federalShareObligated,totalObligated,obligatedDate,declaration_date,obligated_date
16950,1275,1999-05-12T04:00:00.000Z,Severe Storm(s),1013,B-1 ROADS AND BRIDGES,037-54780-00,C - Roads and Bridges,C,Roads and Bridges,Small,Davidson,37.0,Tennessee,TN,2640.85,1980.64,2121.67,1999-06-04T18:03:45.000Z,1999-05-12 04:00:00+00:00,1999-06-04 18:03:45+00:00
16951,1275,1999-05-12T04:00:00.000Z,Severe Storm(s),1014,B-1 LARGE PROJECT DEBRIS REMOVAL,037-54780-00,A - Debris Removal,A,Debris Removal,Large,Davidson,37.0,Tennessee,TN,94148.39,70611.29,74054.13,1999-08-11T23:31:04.000Z,1999-05-12 04:00:00+00:00,1999-08-11 23:31:04+00:00
16954,1275,1999-05-12T04:00:00.000Z,Severe Storm(s),1015,B-1 DEBRIS REMOVAL,037-04620-00,A - Debris Removal,A,Debris Removal,Small,Davidson,37.0,Tennessee,TN,13570.20,10177.65,10796.46,1999-06-04T18:06:14.000Z,1999-05-12 04:00:00+00:00,1999-06-04 18:06:14+00:00
16994,1275,1999-05-12T04:00:00.000Z,Severe Storm(s),1062,AIRPORT,037-52008-00,G - Recreational or Other,G,Recreational or Other,Small,Davidson,37.0,Tennessee,TN,14509.00,10881.75,11430.19,1999-06-07T18:57:04.000Z,1999-05-12 04:00:00+00:00,1999-06-07 18:57:04+00:00
16995,1275,1999-05-12T04:00:00.000Z,Severe Storm(s),1059,AIRFIELD LIGHTING AND SIGNS,037-52008-00,G - Recreational or Other,G,Recreational or Other,Small,Davidson,37.0,Tennessee,TN,15940.00,11955.00,12557.53,1999-06-07T18:57:04.000Z,1999-05-12 04:00:00+00:00,1999-06-07 18:57:04+00:00

In [10]:
# Drop unncessary columns
public_davidson_3 = public_davidson_2.drop(['declarationDate','pwNumber','damageCategoryCode','obligatedDate'], axis=1)
public_davidson_3.head()

,disasterNumber,incidentType,applicationTitle,applicantId,dcc,damageCategory,projectSize,county,countyCode,state,stateCode,projectAmount,federalShareObligated,totalObligated,declaration_date,obligated_date
16950,1275,Severe Storm(s),B-1 ROADS AND BRIDGES,037-54780-00,C,Roads and Bridges,Small,Davidson,37.0,Tennessee,TN,2640.85,1980.64,2121.67,1999-05-12 04:00:00+00:00,1999-06-04 18:03:45+00:00
16951,1275,Severe Storm(s),B-1 LARGE PROJECT DEBRIS REMOVAL,037-54780-00,A,Debris Removal,Large,Davidson,37.0,Tennessee,TN,94148.39,70611.29,74054.13,1999-05-12 04:00:00+00:00,1999-08-11 23:31:04+00:00
16954,1275,Severe Storm(s),B-1 DEBRIS REMOVAL,037-04620-00,A,Debris Removal,Small,Davidson,37.0,Tennessee,TN,13570.20,10177.65,10796.46,1999-05-12 04:00:00+00:00,1999-06-04 18:06:14+00:00
16994,1275,Severe Storm(s),AIRPORT,037-52008-00,G,Recreational or Other,Small,Davidson,37.0,Tennessee,TN,14509.00,10881.75,11430.19,1999-05-12 04:00:00+00:00,1999-06-07 18:57:04+00:00
16995,1275,Severe Storm(s),AIRFIELD LIGHTING AND SIGNS,037-52008-00,G,Recreational or Other,Small,Davidson,37.0,Tennessee,TN,15940.00,11955.00,12557.53,1999-05-12 04:00:00+00:00,1999-06-07 18:57:04+00:00

In [11]:
public_clean = public_davidson_3.rename(columns={"disasterNumber": "Disaster_Number", "incidentType": "Incident_Type", 'applicationTitle':'Application_Title','applicantId':'Applicant_Id','dcc':'DCC','damageCategory':'Damage_Category','projectSize':'Project_Size','county':'County','countyCode':'County_Code','state':'State','stateCode':'State_Code','projectAmount':'Project_Amount','federalShareObligated':'Federal_Share_Obligated','totalObligated':'Total_Obligated'})
public_clean.head()

,Disaster_Number,Incident_Type,Application_Title,Applicant_Id,DCC,Damage_Category,Project_Size,County,County_Code,State,State_Code,Project_Amount,Federal_Share_Obligated,Total_Obligated,declaration_date,obligated_date
16950,1275,Severe Storm(s),B-1 ROADS AND BRIDGES,037-54780-00,C,Roads and Bridges,Small,Davidson,37.0,Tennessee,TN,2640.85,1980.64,2121.67,1999-05-12 04:00:00+00:00,1999-06-04 18:03:45+00:00
16951,1275,Severe Storm(s),B-1 LARGE PROJECT DEBRIS REMOVAL,037-54780-00,A,Debris Removal,Large,Davidson,37.0,Tennessee,TN,94148.39,70611.29,74054.13,1999-05-12 04:00:00+00:00,1999-08-11 23:31:04+00:00
16954,1275,Severe Storm(s),B-1 DEBRIS REMOVAL,037-04620-00,A,Debris Removal,Small,Davidson,37.0,Tennessee,TN,13570.20,10177.65,10796.46,1999-05-12 04:00:00+00:00,1999-06-04 18:06:14+00:00
16994,1275,Severe Storm(s),AIRPORT,037-52008-00,G,Recreational or Other,Small,Davidson,37.0,Tennessee,TN,14509.00,10881.75,11430.19,1999-05-12 04:00:00+00:00,1999-06-07 18:57:04+00:00
16995,1275,Severe Storm(s),AIRFIELD LIGHTING AND SIGNS,037-52008-00,G,Recreational or Other,Small,Davidson,37.0,Tennessee,TN,15940.00,11955.00,12557.53,1999-05-12 04:00:00+00:00,1999-06-07 18:57:04+00:00

In [12]:
# Drop unncessary columns
public_clean_2 = public_clean.drop(['Applicant_Id','County_Code','State'], axis=1)
public_clean_2

,Disaster_Number,Incident_Type,Application_Title,DCC,Damage_Category,Project_Size,County,State_Code,Project_Amount,Federal_Share_Obligated,Total_Obligated,declaration_date,obligated_date
16950,1275,Severe Storm(s),B-1 ROADS AND BRIDGES,C,Roads and Bridges,Small,Davidson,TN,2640.85,1980.64,2121.67,1999-05-12 04:00:00+00:00,1999-06-04 18:03:45+00:00
16951,1275,Severe Storm(s),B-1 LARGE PROJECT DEBRIS REMOVAL,A,Debris Removal,Large,Davidson,TN,94148.39,70611.29,74054.13,1999-05-12 04:00:00+00:00,1999-08-11 23:31:04+00:00
16954,1275,Severe Storm(s),B-1 DEBRIS REMOVAL,A,Debris Removal,Small,Davidson,TN,13570.20,10177.65,10796.46,1999-05-12 04:00:00+00:00,1999-06-04 18:06:14+00:00
16994,1275,Severe Storm(s),AIRPORT,G,Recreational or Other,Small,Davidson,TN,14509.00,10881.75,11430.19,1999-05-12 04:00:00+00:00,1999-06-07 18:57:04+00:00
16995,1275,Severe Storm(s),AIRFIELD LIGHTING AND SIGNS,G,Recreational or Other,Small,Davidson,TN,15940.00,11955.00,12557.53,1999-05-12 04:00:00+00:00,1999-06-07 18:57:04+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
732410,4514,Biological,163972 - Lab Testing Submission 01,B,Protective Measures,Large,Davidson,TN,13471380.00,13471380.00,13471380.00,2020-04-02 04:00:00+00:00,2021-03-23 22:06:43+00:00
733200,4476,Tornado,152099 - DR 4476- EEUNC- Repairs to Fencng,G,Recreational or Other,Small,Davidson,TN,27843.00,20882.25,20882.25,2020-03-05 05:00:00+00:00,2021-04-03 15:38:32+00:00
734581,4476,Tornado,137749 - Debris Removal from other Depts.,A,Debris Removal,Large,Davidson,TN,250430.60,187822.95,187822.95,2020-03-05 05:00:00+00:00,2021-04-22 15:57:59+00:00
736017,4550,Severe Storm(s),149510 - Roof damages to schools and other depts,E,Public Buildings,Small,Davidson,TN,101158.75,75869.06,75869.06,2020-07-09 04:00:00+00:00,2021-05-08 18:32:16+00:00
736946,4514,Biological,155557 - Health Department Submission 01,B,Protective Measures,Large,Davidson,TN,888843.88,888843.88,888843.88,2020-04-02 04:00:00+00:00,2021-05-21 00:56:25+00:00

In [13]:
public_clean_3 = public_clean_2[public_clean_2["Incident_Type"].str.contains("Biological")==False]
public_clean_3

,Disaster_Number,Incident_Type,Application_Title,DCC,Damage_Category,Project_Size,County,State_Code,Project_Amount,Federal_Share_Obligated,Total_Obligated,declaration_date,obligated_date
16950,1275,Severe Storm(s),B-1 ROADS AND BRIDGES,C,Roads and Bridges,Small,Davidson,TN,2640.85,1980.64,2121.67,1999-05-12 04:00:00+00:00,1999-06-04 18:03:45+00:00
16951,1275,Severe Storm(s),B-1 LARGE PROJECT DEBRIS REMOVAL,A,Debris Removal,Large,Davidson,TN,94148.39,70611.29,74054.13,1999-05-12 04:00:00+00:00,1999-08-11 23:31:04+00:00
16954,1275,Severe Storm(s),B-1 DEBRIS REMOVAL,A,Debris Removal,Small,Davidson,TN,13570.20,10177.65,10796.46,1999-05-12 04:00:00+00:00,1999-06-04 18:06:14+00:00
16994,1275,Severe Storm(s),AIRPORT,G,Recreational or Other,Small,Davidson,TN,14509.00,10881.75,11430.19,1999-05-12 04:00:00+00:00,1999-06-07 18:57:04+00:00
16995,1275,Severe Storm(s),AIRFIELD LIGHTING AND SIGNS,G,Recreational or Other,Small,Davidson,TN,15940.00,11955.00,12557.53,1999-05-12 04:00:00+00:00,1999-06-07 18:57:04+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
731141,4550,Severe Storm(s),149509 - Tennis court and boardwalk,G,Recreational or Other,Small,Davidson,TN,78333.92,58750.44,58750.44,2020-07-09 04:00:00+00:00,2021-03-07 23:20:47+00:00
731889,4476,Tornado,160139 - Dept of Public Works,A,Debris Removal,Large,Davidson,TN,2361811.88,1771358.91,1771358.91,2020-03-05 05:00:00+00:00,2021-03-17 19:58:13+00:00
733200,4476,Tornado,152099 - DR 4476- EEUNC- Repairs to Fencng,G,Recreational or Other,Small,Davidson,TN,27843.00,20882.25,20882.25,2020-03-05 05:00:00+00:00,2021-04-03 15:38:32+00:00
734581,4476,Tornado,137749 - Debris Removal from other Depts.,A,Debris Removal,Large,Davidson,TN,250430.60,187822.95,187822.95,2020-03-05 05:00:00+00:00,2021-04-22 15:57:59+00:00
736017,4550,Severe Storm(s),149510 - Roof damages to schools and other depts,E,Public Buildings,Small,Davidson,TN,101158.75,75869.06,75869.06,2020-07-09 04:00:00+00:00,2021-05-08 18:32:16+00:00

In [14]:
public_project = public_clean_3
public_project

,Disaster_Number,Incident_Type,Application_Title,DCC,Damage_Category,Project_Size,County,State_Code,Project_Amount,Federal_Share_Obligated,Total_Obligated,declaration_date,obligated_date
16950,1275,Severe Storm(s),B-1 ROADS AND BRIDGES,C,Roads and Bridges,Small,Davidson,TN,2640.85,1980.64,2121.67,1999-05-12 04:00:00+00:00,1999-06-04 18:03:45+00:00
16951,1275,Severe Storm(s),B-1 LARGE PROJECT DEBRIS REMOVAL,A,Debris Removal,Large,Davidson,TN,94148.39,70611.29,74054.13,1999-05-12 04:00:00+00:00,1999-08-11 23:31:04+00:00
16954,1275,Severe Storm(s),B-1 DEBRIS REMOVAL,A,Debris Removal,Small,Davidson,TN,13570.20,10177.65,10796.46,1999-05-12 04:00:00+00:00,1999-06-04 18:06:14+00:00
16994,1275,Severe Storm(s),AIRPORT,G,Recreational or Other,Small,Davidson,TN,14509.00,10881.75,11430.19,1999-05-12 04:00:00+00:00,1999-06-07 18:57:04+00:00
16995,1275,Severe Storm(s),AIRFIELD LIGHTING AND SIGNS,G,Recreational or Other,Small,Davidson,TN,15940.00,11955.00,12557.53,1999-05-12 04:00:00+00:00,1999-06-07 18:57:04+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
731141,4550,Severe Storm(s),149509 - Tennis court and boardwalk,G,Recreational or Other,Small,Davidson,TN,78333.92,58750.44,58750.44,2020-07-09 04:00:00+00:00,2021-03-07 23:20:47+00:00
731889,4476,Tornado,160139 - Dept of Public Works,A,Debris Removal,Large,Davidson,TN,2361811.88,1771358.91,1771358.91,2020-03-05 05:00:00+00:00,2021-03-17 19:58:13+00:00
733200,4476,Tornado,152099 - DR 4476- EEUNC- Repairs to Fencng,G,Recreational or Other,Small,Davidson,TN,27843.00,20882.25,20882.25,2020-03-05 05:00:00+00:00,2021-04-03 15:38:32+00:00
734581,4476,Tornado,137749 - Debris Removal from other Depts.,A,Debris Removal,Large,Davidson,TN,250430.60,187822.95,187822.95,2020-03-05 05:00:00+00:00,2021-04-22 15:57:59+00:00
736017,4550,Severe Storm(s),149510 - Roof damages to schools and other depts,E,Public Buildings,Small,Davidson,TN,101158.75,75869.06,75869.06,2020-07-09 04:00:00+00:00,2021-05-08 18:32:16+00:00

# Cleaning Owners Dataset

In [15]:
owners.head()

,disasterNumber,state,county,city,zipCode,validRegistrations,averageFemaInspectedDamage,totalInspected,totalDamage,noFemaInspectedDamage,...,approvedForFemaAssistance,totalApprovedIhpAmount,repairReplaceAmount,rentalAmount,otherNeedsAmount,approvedBetween1And10000,approvedBetween10001And25000,approvedBetween25001AndMax,totalMaxGrants,id
0,1439,TX,Harris (County),HOUSTON,77047,6,1205.226667,6,7231.36,2,...,4,12695.24,7033.24,5662.0,0.00,2,2,0,0,60bb448ca0ee349d71c9185d
1,1439,TX,Harris (County),HOUSTON,77022,5,1414.474000,4,7072.37,1,...,3,8945.23,2467.74,1156.0,5321.49,2,1,0,0,60bb448ca0ee349d71c9184a
2,1439,TX,Jasper (County),KIRBYVILLE,75956,24,2187.857500,23,52508.58,2,...,19,51295.16,30765.80,4092.0,16437.36,16,1,2,0,60bb448ca0ee349d71c91837
3,1439,TX,Harris (County),HOUSTON,77014,2,2379.300000,2,4758.60,0,...,2,8534.10,4366.10,4168.0,0.00,1,1,0,0,60bb448ca0ee349d71c91842
4,1439,TX,Harris (County),JERSEY VILLAGE,77040,2,5823.655000,2,11647.31,0,...,1,2089.50,2089.50,0.0,0.00,1,0,0,0,60bb448ca0ee349d71c91857

In [16]:
# Filtering data down to State Code TN
owners_tn = owners[owners['state']=='TN']
owners_tn.head()

,disasterNumber,state,county,city,zipCode,validRegistrations,averageFemaInspectedDamage,totalInspected,totalDamage,noFemaInspectedDamage,...,approvedForFemaAssistance,totalApprovedIhpAmount,repairReplaceAmount,rentalAmount,otherNeedsAmount,approvedBetween1And10000,approvedBetween10001And25000,approvedBetween25001AndMax,totalMaxGrants,id
327,1441,TN,Marshall (County),BELFAST,37019,1,2604.100000,1,2604.10,0,...,0,0.00,0.00,0.0,0.00,0,0,0,0,60bb448ca0ee349d71c919c7
328,1441,TN,Coffee (County),TULLAHOMA,37388,1,0.000000,1,0.00,1,...,0,0.00,0.00,0.0,0.00,0,0,0,0,60bb448ca0ee349d71c919da
329,1441,TN,Morgan (County),PETROS,37840,2,70617.790000,2,141235.58,0,...,2,30138.56,9247.56,2373.0,18518.00,0,1,1,1,60bb448ca0ee349d71c919ec
330,1441,TN,Roane (County),OLIVER SPRINGS,37840,13,4172.725385,8,54245.43,1,...,5,27277.71,10585.25,3000.0,13692.46,3,1,1,0,60bb448ca0ee349d71c919ed
339,1441,TN,Bedford (County),WARTRACE,37183,14,13495.834290,3,188941.68,0,...,1,118.03,0.00,0.0,118.03,1,0,0,0,60bb448ca0ee349d71c919d4

In [17]:
# Cleaning 'county' column to remove (County)
owners_tn['county'] = owners_tn['county'].str.replace(r'\(.*\)','',regex=True)
owners_tn

<ipython-input-17-7350f0d6d3c6>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  owners_tn['county'] = owners_tn['county'].str.replace(r'\(.*\)','',regex=True)

,disasterNumber,state,county,city,zipCode,validRegistrations,averageFemaInspectedDamage,totalInspected,totalDamage,noFemaInspectedDamage,...,approvedForFemaAssistance,totalApprovedIhpAmount,repairReplaceAmount,rentalAmount,otherNeedsAmount,approvedBetween1And10000,approvedBetween10001And25000,approvedBetween25001AndMax,totalMaxGrants,id
327,1441,TN,Marshall,BELFAST,37019,1,2604.100000,1,2604.10,0,...,0,0.00,0.00,0.0,0.00,0,0,0,0,60bb448ca0ee349d71c919c7
328,1441,TN,Coffee,TULLAHOMA,37388,1,0.000000,1,0.00,1,...,0,0.00,0.00,0.0,0.00,0,0,0,0,60bb448ca0ee349d71c919da
329,1441,TN,Morgan,PETROS,37840,2,70617.790000,2,141235.58,0,...,2,30138.56,9247.56,2373.0,18518.00,0,1,1,1,60bb448ca0ee349d71c919ec
330,1441,TN,Roane,OLIVER SPRINGS,37840,13,4172.725385,8,54245.43,1,...,5,27277.71,10585.25,3000.0,13692.46,3,1,1,0,60bb448ca0ee349d71c919ed
339,1441,TN,Bedford,WARTRACE,37183,14,13495.834290,3,188941.68,0,...,1,118.03,0.00,0.0,118.03,1,0,0,0,60bb448ca0ee349d71c919d4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115580,4601,TN,Davidson,NASHVILLE,37220,22,972.516818,9,21395.37,0,...,9,22381.48,17925.48,4456.0,0.00,7,2,0,0,60bb449ca0ee349d71cae31c
115581,4601,TN,Wilson,JOHNSON CITY,37604,1,0.000000,0,0.00,0,...,0,0.00,0.00,0.0,0.00,0,0,0,0,60bb449ca0ee349d71cae321
115602,4601,TN,Williamson,FRANKLIN,37064,18,499.556667,5,8992.02,1,...,3,10944.28,7586.30,3078.0,279.98,2,1,0,0,60bb449ca0ee349d71cae2fb
115603,4601,TN,Davidson,NASHVILLE,37208,2,2828.300000,1,5656.60,0,...,0,0.00,0.00,0.0,0.00,0,0,0,0,60bb449ca0ee349d71cae313
115604,4601,TN,Davidson,ARLINGTON,38002,1,0.000000,0,0.00,0,...,0,0.00,0.00,0.0,0.00,0,0,0,0,60bb449ca0ee349d71cae323

In [18]:
# Filter dataset to Davidson county. Having issues filtering by county so I used city.
owners_davidson = owners_tn[owners_tn['city']=='NASHVILLE']
owners_davidson.head()

,disasterNumber,state,county,city,zipCode,validRegistrations,averageFemaInspectedDamage,totalInspected,totalDamage,noFemaInspectedDamage,...,approvedForFemaAssistance,totalApprovedIhpAmount,repairReplaceAmount,rentalAmount,otherNeedsAmount,approvedBetween1And10000,approvedBetween10001And25000,approvedBetween25001AndMax,totalMaxGrants,id
2721,1464,TN,Davidson,NASHVILLE,37217,2,2391.555000,2,4783.11,0,...,2,4783.11,4664.07,0.0,119.04,1,1,0,0,60bb448ca0ee349d71c9234a
2733,1464,TN,Davidson,NASHVILLE,37208,3,229.333333,1,688.00,0,...,1,688.00,688.00,0.0,0.00,1,0,0,0,60bb448ca0ee349d71c92343
2744,1464,TN,Davidson,NASHVILLE,37211,28,1777.151786,24,49760.25,6,...,11,17651.48,15623.48,2028.0,0.00,11,0,0,0,60bb448ca0ee349d71c92346
2757,1464,TN,Davidson,NASHVILLE,37205,1,5006.700000,1,5006.70,0,...,1,3252.08,3084.33,0.0,167.75,1,0,0,0,60bb448ca0ee349d71c92340
2766,1464,TN,Davidson,NASHVILLE,37210,1,0.000000,0,0.00,0,...,0,0.00,0.00,0.0,0.00,0,0,0,0,60bb448ca0ee349d71c92345

In [19]:
# Drop Columns
owners_davidson_2 = owners_davidson.drop(['validRegistrations','approvedBetween1And10000','approvedBetween25001AndMax','totalMaxGrants','id'], axis=1)
owners_davidson_2.head()

,disasterNumber,state,county,city,zipCode,averageFemaInspectedDamage,totalInspected,totalDamage,noFemaInspectedDamage,femaInspectedDamageBetween1And10000,femaInspectedDamageBetween10001And20000,femaInspectedDamageBetween20001And30000,femaInspectedDamageGreaterThan30000,approvedForFemaAssistance,totalApprovedIhpAmount,repairReplaceAmount,rentalAmount,otherNeedsAmount,approvedBetween10001And25000
2721,1464,TN,Davidson,NASHVILLE,37217,2391.555000,2,4783.11,0,2,0,0,0,2,4783.11,4664.07,0.0,119.04,1
2733,1464,TN,Davidson,NASHVILLE,37208,229.333333,1,688.00,0,1,0,0,0,1,688.00,688.00,0.0,0.00,0
2744,1464,TN,Davidson,NASHVILLE,37211,1777.151786,24,49760.25,6,17,1,0,0,11,17651.48,15623.48,2028.0,0.00,0
2757,1464,TN,Davidson,NASHVILLE,37205,5006.700000,1,5006.70,0,1,0,0,0,1,3252.08,3084.33,0.0,167.75,0
2766,1464,TN,Davidson,NASHVILLE,37210,0.000000,0,0.00,0,0,0,0,0,0,0.00,0.00,0.0,0.00,0

In [20]:
# Drop Columns
owners_davidson_3 = owners_davidson_2.drop(['noFemaInspectedDamage','femaInspectedDamageBetween1And10000','femaInspectedDamageBetween10001And20000','femaInspectedDamageBetween20001And30000','femaInspectedDamageGreaterThan30000','approvedForFemaAssistance','approvedBetween10001And25000'], axis=1)
owners_davidson_3.head()

,disasterNumber,state,county,city,zipCode,averageFemaInspectedDamage,totalInspected,totalDamage,totalApprovedIhpAmount,repairReplaceAmount,rentalAmount,otherNeedsAmount
2721,1464,TN,Davidson,NASHVILLE,37217,2391.555000,2,4783.11,4783.11,4664.07,0.0,119.04
2733,1464,TN,Davidson,NASHVILLE,37208,229.333333,1,688.00,688.00,688.00,0.0,0.00
2744,1464,TN,Davidson,NASHVILLE,37211,1777.151786,24,49760.25,17651.48,15623.48,2028.0,0.00
2757,1464,TN,Davidson,NASHVILLE,37205,5006.700000,1,5006.70,3252.08,3084.33,0.0,167.75
2766,1464,TN,Davidson,NASHVILLE,37210,0.000000,0,0.00,0.00,0.00,0.0,0.00

In [21]:
owners_davidson_4 = owners_davidson_3.rename(columns={"disasterNumber": "Disaster_Number", "state": "State", 'county':'County','city':'City','zipCode':'Zip_Code','averageFemaInspectedDamage':'Avg_Inspected_Damage','totalInspected':'Total_Inspected','totalDamage':'Total_Damage','totalApprovedIhpAmount':'Total_Approved','repairReplaceAmount':'Repair_Replace_Amount','rentalAmount':'Rental_Amount','otherNeedsAmount':'Other_Needs_Amount'})
owners_davidson_4

,Disaster_Number,State,County,City,Zip_Code,Avg_Inspected_Damage,Total_Inspected,Total_Damage,Total_Approved,Repair_Replace_Amount,Rental_Amount,Other_Needs_Amount
2721,1464,TN,Davidson,NASHVILLE,37217,2391.555000,2,4783.11,4783.11,4664.07,0.0,119.04
2733,1464,TN,Davidson,NASHVILLE,37208,229.333333,1,688.00,688.00,688.00,0.0,0.00
2744,1464,TN,Davidson,NASHVILLE,37211,1777.151786,24,49760.25,17651.48,15623.48,2028.0,0.00
2757,1464,TN,Davidson,NASHVILLE,37205,5006.700000,1,5006.70,3252.08,3084.33,0.0,167.75
2766,1464,TN,Davidson,NASHVILLE,37210,0.000000,0,0.00,0.00,0.00,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
115545,4601,TN,Davidson,NASHVILLE,37204,2158.942500,8,34543.08,17638.69,7358.69,10280.0,0.00
115560,4601,TN,Davidson,NASHVILLE,37218,0.000000,0,0.00,0.00,0.00,0.0,0.00
115561,4601,TN,Williamson,NASHVILLE,37221,0.000000,0,0.00,0.00,0.00,0.0,0.00
115580,4601,TN,Davidson,NASHVILLE,37220,972.516818,9,21395.37,22381.48,17925.48,4456.0,0.00
115603,4601,TN,Davidson,NASHVILLE,37208,2828.300000,1,5656.60,0.00,0.00,0.0,0.00

In [22]:
owners_davidson_4.County.unique()

array(['Davidson ', 'Williamson ', 'Macon ', 'Humphreys ', 'Cheatham ',
       'Sumner '], dtype=object)

In [23]:
owners_davidson_5 = owners_davidson_4[owners_davidson_4['County']=='Davidson ']
owners_davidson_5

,Disaster_Number,State,County,City,Zip_Code,Avg_Inspected_Damage,Total_Inspected,Total_Damage,Total_Approved,Repair_Replace_Amount,Rental_Amount,Other_Needs_Amount
2721,1464,TN,Davidson,NASHVILLE,37217,2391.555000,2,4783.11,4783.11,4664.07,0.0,119.04
2733,1464,TN,Davidson,NASHVILLE,37208,229.333333,1,688.00,688.00,688.00,0.0,0.00
2744,1464,TN,Davidson,NASHVILLE,37211,1777.151786,24,49760.25,17651.48,15623.48,2028.0,0.00
2757,1464,TN,Davidson,NASHVILLE,37205,5006.700000,1,5006.70,3252.08,3084.33,0.0,167.75
2766,1464,TN,Davidson,NASHVILLE,37210,0.000000,0,0.00,0.00,0.00,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
115530,4601,TN,Davidson,NASHVILLE,37203,459.075000,1,918.15,0.00,0.00,0.0,0.00
115545,4601,TN,Davidson,NASHVILLE,37204,2158.942500,8,34543.08,17638.69,7358.69,10280.0,0.00
115560,4601,TN,Davidson,NASHVILLE,37218,0.000000,0,0.00,0.00,0.00,0.0,0.00
115580,4601,TN,Davidson,NASHVILLE,37220,972.516818,9,21395.37,22381.48,17925.48,4456.0,0.00
115603,4601,TN,Davidson,NASHVILLE,37208,2828.300000,1,5656.60,0.00,0.00,0.0,0.00

In [24]:
owners_project = owners_davidson_5.drop(['City'], axis=1)
owners_project

,Disaster_Number,State,County,Zip_Code,Avg_Inspected_Damage,Total_Inspected,Total_Damage,Total_Approved,Repair_Replace_Amount,Rental_Amount,Other_Needs_Amount
2721,1464,TN,Davidson,37217,2391.555000,2,4783.11,4783.11,4664.07,0.0,119.04
2733,1464,TN,Davidson,37208,229.333333,1,688.00,688.00,688.00,0.0,0.00
2744,1464,TN,Davidson,37211,1777.151786,24,49760.25,17651.48,15623.48,2028.0,0.00
2757,1464,TN,Davidson,37205,5006.700000,1,5006.70,3252.08,3084.33,0.0,167.75
2766,1464,TN,Davidson,37210,0.000000,0,0.00,0.00,0.00,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...
115530,4601,TN,Davidson,37203,459.075000,1,918.15,0.00,0.00,0.0,0.00
115545,4601,TN,Davidson,37204,2158.942500,8,34543.08,17638.69,7358.69,10280.0,0.00
115560,4601,TN,Davidson,37218,0.000000,0,0.00,0.00,0.00,0.0,0.00
115580,4601,TN,Davidson,37220,972.516818,9,21395.37,22381.48,17925.48,4456.0,0.00
115603,4601,TN,Davidson,37208,2828.300000,1,5656.60,0.00,0.00,0.0,0.00

# Manipulating clean data sets Owners and Public
public_project

owners_project

In [27]:
public_project.head()

,Disaster_Number,Incident_Type,Application_Title,DCC,Damage_Category,Project_Size,County,State_Code,Project_Amount,Federal_Share_Obligated,Total_Obligated,declaration_date,obligated_date
16950,1275,Severe Storm(s),B-1 ROADS AND BRIDGES,C,Roads and Bridges,Small,Davidson,TN,2640.85,1980.64,2121.67,1999-05-12 04:00:00+00:00,1999-06-04 18:03:45+00:00
16951,1275,Severe Storm(s),B-1 LARGE PROJECT DEBRIS REMOVAL,A,Debris Removal,Large,Davidson,TN,94148.39,70611.29,74054.13,1999-05-12 04:00:00+00:00,1999-08-11 23:31:04+00:00
16954,1275,Severe Storm(s),B-1 DEBRIS REMOVAL,A,Debris Removal,Small,Davidson,TN,13570.20,10177.65,10796.46,1999-05-12 04:00:00+00:00,1999-06-04 18:06:14+00:00
16994,1275,Severe Storm(s),AIRPORT,G,Recreational or Other,Small,Davidson,TN,14509.00,10881.75,11430.19,1999-05-12 04:00:00+00:00,1999-06-07 18:57:04+00:00
16995,1275,Severe Storm(s),AIRFIELD LIGHTING AND SIGNS,G,Recreational or Other,Small,Davidson,TN,15940.00,11955.00,12557.53,1999-05-12 04:00:00+00:00,1999-06-07 18:57:04+00:00

In [34]:
test = public_project[public_project['Incident_Type']== 'Tornado']
test

,Disaster_Number,Incident_Type,Application_Title,DCC,Damage_Category,Project_Size,County,State_Code,Project_Amount,Federal_Share_Obligated,Total_Obligated,declaration_date,obligated_date
712652,4476,Tornado,136065 - APP CERT - MNAA - Emergency Protectiv...,B,Protective Measures,Small,Davidson,TN,11131.10,8348.33,8348.33,2020-03-05 05:00:00+00:00,2020-06-27 03:11:35+00:00
713021,4476,Tornado,137754 - Emergency Protective Measure-Fire Dept,B,Protective Measures,Large,Davidson,TN,132352.23,99264.17,99264.17,2020-03-05 05:00:00+00:00,2020-07-01 23:49:53+00:00
714877,4476,Tornado,138256 - Security _ St John AME _ SELF CERT,B,Protective Measures,Small,Davidson,TN,3467.00,2600.25,2600.25,2020-03-05 05:00:00+00:00,2020-07-24 06:03:32+00:00
715929,4476,Tornado,136710 - Building: Meigs Middle School - Metro...,E,Public Buildings,Large,Davidson,TN,1052793.50,789595.12,789595.12,2020-03-05 05:00:00+00:00,2020-08-07 02:28:37+00:00
718061,4476,Tornado,136067 - MNAA - Chemical Spill Remediation,A,Debris Removal,Large,Davidson,TN,1000000.00,750000.00,750000.00,2020-03-05 05:00:00+00:00,2020-09-04 23:50:32+00:00
720690,4476,Tornado,136704 - Debris Removal County Wide DPW,A,Debris Removal,Large,Davidson,TN,4209443.62,3157082.72,3157082.72,2020-03-05 05:00:00+00:00,2020-10-09 20:10:46+00:00
723963,4476,Tornado,"136706 - APP CERT Signage, sidewalks and alleys",C,Roads and Bridges,Small,Davidson,TN,75101.46,56326.10,56326.10,2020-03-05 05:00:00+00:00,2020-11-19 22:43:51+00:00
725074,4476,Tornado,137619 - Emergency Protective Measures - East ...,B,Protective Measures,Large,Davidson,TN,182878.38,137158.79,137158.79,2020-03-05 05:00:00+00:00,2020-12-05 03:40:14+00:00
725075,4476,Tornado,136713 - App Cert -Communications,F,Public Utilities,Small,Davidson,TN,27318.05,20488.54,20488.54,2020-03-05 05:00:00+00:00,2020-12-05 03:40:14+00:00
726251,4476,Tornado,"136066 - MNAA - Temporary, Rental Office Trailer",B,Protective Measures,Small,Davidson,TN,50000.00,37500.00,37500.00,2020-03-05 05:00:00+00:00,2020-12-19 19:14:58+00:00
729257,4476,Tornado,137206 - DR 4476 TN - Donelson Christian Acad...,A,Debris Removal,Small,Davidson,TN,35644.64,26733.48,26733.48,2020-03-05 05:00:00+00:00,2021-02-09 00:01:53+00:00
729521,4476,Tornado,137755 - EPM Nashville Public Schools Small Ce...,B,Protective Measures,Small,Davidson,TN,96095.65,72071.74,72071.74,2020-03-05 05:00:00+00:00,2021-02-13 03:35:47+00:00
731889,4476,Tornado,160139 - Dept of Public Works,A,Debris Removal,Large,Davidson,TN,2361811.88,1771358.91,1771358.91,2020-03-05 05:00:00+00:00,2021-03-17 19:58:13+00:00
733200,4476,Tornado,152099 - DR 4476- EEUNC- Repairs to Fencng,G,Recreational or Other,Small,Davidson,TN,27843.00,20882.25,20882.25,2020-03-05 05:00:00+00:00,2021-04-03 15:38:32+00:00
734581,4476,Tornado,137749 - Debris Removal from other Depts.,A,Debris Removal,Large,Davidson,TN,250430.60,187822.95,187822.95,2020-03-05 05:00:00+00:00,2021-04-22 15:57:59+00:00

In [25]:
public_project.to_csv(r'C:\Users\matth\Documents\NSS\Projects\CAPSTONE\Nashville_Community_Resources\public_infrastructure.csv', index = False)

In [26]:
public_project.to_csv(r'C:\Users\matth\Documents\NSS\Projects\CAPSTONE\Nashville_Community_Resources\owners.csv', index = False)